---

services:
  nginx:
    image: nginx:local
    build:
      context: .
    volumes:
      - ./lib/resty/solr:/usr/local/openresty/site/lualib/resty/solr
    configs:
      - source: nginx.conf
        target: /usr/local/openresty/nginx/conf/nginx.conf
    network_mode: host
    ports:
      - "8080:8080"

configs:
  nginx.conf:
    content: |
      worker_processes 2;

      events {
        worker_connections 1024;
      }

      error_log /dev/stderr;

      http {
        sendfile on;

        init_worker_by_lua_block {
          module = require("resty.solr.args")
        }

        upstream upstream {
          server 127.0.0.1:8081;
        }

        server {
          listen 8080;
          server_name localhost;

          access_log /dev/stdout;
          error_log /dev/stderr;

          location /test {
            content_by_lua_block {
              ngx.say(module
                .new()
                :wildcard_query(ngx.var.arg_q)
                :start(ngx.var.arg_start)
                :output_json(ngx.var.arg_o == 'json')
                :filter('arg_fy', '{!tag=YEAR}year', tonumber(ngx.var.arg_fy))
                :filter('arg_fm', '{!tag=MONTH}month', tonumber(ngx.var.arg_fm))
                :build(1) .. '');
            }
          }

          location /search {
            #proxy_pass http://upstream;

            set_by_lua_block $$args {
              return module
                .new()
                :wildcard_query(ngx.var.arg_q)
                :start(ngx.var.arg_start)
                :output_json(ngx.var.arg_o == 'json')
                :filter('arg_fy', '{!tag=YEAR}year', tonumber(ngx.var.arg_fy))
                :filter('arg_fm', '{!tag=MONTH}month', tonumber(ngx.var.arg_fm))
                :build();
            }
          }
        }
      }
